FROM hub.c.163.com/library/java:latest
VOLUME /tmp
ADD springBoot.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]